[project]
name = "science-notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "torch>=2.8.0",
    "transformers>=4.56.0",
]
